.PHONY: clean All

All:
	@echo "----------Building project:[ FirstCode - Debug ]----------"
	@cd "FirstCode" && "$(MAKE)" -f  "FirstCode.mk"
clean:
	@echo "----------Cleaning project:[ FirstCode - Debug ]----------"
	@cd "FirstCode" && "$(MAKE)" -f  "FirstCode.mk" clean
